//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPNHATTHONGTIN
    {
        public string MATAILIEU { get; set; }
        public string MAMUA { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual MUATAILIEUMOI MUATAILIEUMOI { get; set; }
        public virtual TAILIEU TAILIEU { get; set; }
    }
}
