//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUMUON
    {
        public string MAPHIEUMUON { get; set; }
        public string MATAILIEU { get; set; }
        public float PHIMUON { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual PHIEUMUON PHIEUMUON { get; set; }
        public virtual TAILIEU TAILIEU { get; set; }
    }
}
