//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDATTRUOC
    {
        public string MAMUON { get; set; }
        public string MATAILIEU { get; set; }
        public Nullable<float> PHIMUON { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual DATMUONTRUOC DATMUONTRUOC { get; set; }
        public virtual TAILIEU TAILIEU { get; set; }
    }
}
