//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATMUONTRUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATMUONTRUOC()
        {
            this.CHITIETDATTRUOCs = new HashSet<CHITIETDATTRUOC>();
        }
    
        public string MAMUON { get; set; }
        public System.DateTime NGAYDAT { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> HANLAYSACH { get; set; }
        public string MASOTHE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATTRUOC> CHITIETDATTRUOCs { get; set; }
        public virtual THEBANDOC THEBANDOC { get; set; }
    }
}
