//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATPHONG
    {
        public DATPHONG()
        {
            this.PHONGHOC1 = new HashSet<PHONGHOC>();
        }
    
        public string MASOTHE { get; set; }
        public string MADATPHONG { get; set; }
        public System.DateTime NGAYDAT { get; set; }
        public System.DateTime THOIGIANBATDAU { get; set; }
        public System.DateTime THOIGIANKETTHUC { get; set; }
        public string TRANGTHAI { get; set; }
        public string YEUCAU { get; set; }
        public string MAPHONG { get; set; }
    
        public virtual PHONGHOC PHONGHOC { get; set; }
        public virtual THEBANDOC THEBANDOC { get; set; }
        public virtual ICollection<PHONGHOC> PHONGHOC1 { get; set; }
    }
}
