//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCGIA
    {
        public DOCGIA()
        {
            this.THEBANDOC = new HashSet<THEBANDOC>();
        }
    
        public string MATHANHVIEN { get; set; }
        public string TENTV { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string GIOITINH { get; set; }
        public string NGHENGHIEP { get; set; }
        public string SODIENTHOAI { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string VAITRO { get; set; }
        public string DIACHI { get; set; }
        public string TENTRUONG { get; set; }
        public string KHOAHOC { get; set; }
        public string EMAIL { get; set; }
        public string GHICHU { get; set; }
    
        public virtual ICollection<THEBANDOC> THEBANDOC { get; set; }
    }
}
