//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAHANTAILIEU
    {
        public GIAHANTAILIEU()
        {
            this.PHIEUMUON1 = new HashSet<PHIEUMUON>();
        }
    
        public string MAGIAHAN { get; set; }
        public System.DateTime NGAYGIAHAN { get; set; }
        public System.DateTime HANMOI { get; set; }
        public string TRANGTHAI { get; set; }
        public string MAPHIEUMUON { get; set; }
        public string YEUCAU { get; set; }
    
        public virtual PHIEUMUON PHIEUMUON { get; set; }
        public virtual ICollection<PHIEUMUON> PHIEUMUON1 { get; set; }
    }
}
