//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYTHUVIENEntities1 : DbContext
    {
        public QUANLYTHUVIENEntities1()
            : base("name=QUANLYTHUVIENEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAPNHATTHONGTIN> CAPNHATTHONGTIN { get; set; }
        public virtual DbSet<CHITIETDATTRUOC> CHITIETDATTRUOC { get; set; }
        public virtual DbSet<CHITIETPHIEUMUON> CHITIETPHIEUMUON { get; set; }
        public virtual DbSet<DATMUONTRUOC> DATMUONTRUOC { get; set; }
        public virtual DbSet<DATPHONG> DATPHONG { get; set; }
        public virtual DbSet<DOCGIA> DOCGIA { get; set; }
        public virtual DbSet<GIAHANTAILIEU> GIAHANTAILIEU { get; set; }
        public virtual DbSet<MUATAILIEUMOI> MUATAILIEUMOI { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<PHIEUMUON> PHIEUMUON { get; set; }
        public virtual DbSet<PHIEUPHAT> PHIEUPHAT { get; set; }
        public virtual DbSet<PHONGHOC> PHONGHOC { get; set; }
        public virtual DbSet<QUANLYTAILIEU> QUANLYTAILIEU { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TAILIEU> TAILIEU { get; set; }
        public virtual DbSet<THANHLYTAILIEU> THANHLYTAILIEU { get; set; }
        public virtual DbSet<THEBANDOC> THEBANDOC { get; set; }
    }
}
