//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYTHUVIENEntities : DbContext
    {
        public QUANLYTHUVIENEntities()
            : base("name=QUANLYTHUVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAPNHATTHONGTIN> CAPNHATTHONGTIN { get; set; }
        public DbSet<CHITIETDATTRUOC> CHITIETDATTRUOC { get; set; }
        public DbSet<CHITIETPHIEUMUON> CHITIETPHIEUMUON { get; set; }
        public DbSet<DATMUONTRUOC> DATMUONTRUOC { get; set; }
        public DbSet<DATPHONG> DATPHONG { get; set; }
        public DbSet<DOCGIA> DOCGIA { get; set; }
        public DbSet<GIAHANTAILIEU> GIAHANTAILIEU { get; set; }
        public DbSet<MUATAILIEUMOI> MUATAILIEUMOI { get; set; }
        public DbSet<NHANVIEN> NHANVIEN { get; set; }
        public DbSet<PHIEUMUON> PHIEUMUON { get; set; }
        public DbSet<PHIEUPHAT> PHIEUPHAT { get; set; }
        public DbSet<PHONGHOC> PHONGHOC { get; set; }
        public DbSet<QUANLYTAILIEU> QUANLYTAILIEU { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TAILIEU> TAILIEU { get; set; }
        public DbSet<THANHLYTAILIEU> THANHLYTAILIEU { get; set; }
        public DbSet<THEBANDOC> THEBANDOC { get; set; }
        public DbSet<BorrowHistoryVM> BorrowHistoryVM { get; set; }
        public DbSet<CartItem> CartItem { get; set; }


    }
}
