//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYTHUVIENEntities : DbContext
    {
        public QUANLYTHUVIENEntities()
            : base("name=QUANLYTHUVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAPNHATTHONGTIN> CAPNHATTHONGTINs { get; set; }
        public virtual DbSet<CHITIETDATTRUOC> CHITIETDATTRUOCs { get; set; }
        public virtual DbSet<CHITIETPHIEUMUON> CHITIETPHIEUMUONs { get; set; }
        public virtual DbSet<DATMUONTRUOC> DATMUONTRUOCs { get; set; }
        public virtual DbSet<DATPHONG> DATPHONGs { get; set; }
        public virtual DbSet<DOCGIA> DOCGIAs { get; set; }
        public virtual DbSet<GIAHANTAILIEU> GIAHANTAILIEUx { get; set; }
        public virtual DbSet<MUATAILIEUMOI> MUATAILIEUMOIs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUMUON> PHIEUMUONs { get; set; }
        public virtual DbSet<PHIEUPHAT> PHIEUPHATs { get; set; }
        public virtual DbSet<PHONGHOC> PHONGHOCs { get; set; }
        public virtual DbSet<QUANLYTAILIEU> QUANLYTAILIEUx { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAILIEU> TAILIEUx { get; set; }
        public virtual DbSet<THANHLYTAILIEU> THANHLYTAILIEUx { get; set; }
        public virtual DbSet<THEBANDOC> THEBANDOCs { get; set; }
    }
}
