//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUATAILIEUMOI
    {
        public MUATAILIEUMOI()
        {
            this.CAPNHATTHONGTIN = new HashSet<CAPNHATTHONGTIN>();
        }
    
        public string MAMUA { get; set; }
        public string MANV { get; set; }
        public System.DateTime NGAYMUA { get; set; }
        public string NHAXUATBAN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual ICollection<CAPNHATTHONGTIN> CAPNHATTHONGTIN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
