//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUATAILIEUMOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUATAILIEUMOI()
        {
            this.CAPNHATTHONGTINs = new HashSet<CAPNHATTHONGTIN>();
        }
    
        public string MAMUA { get; set; }
        public string MANV { get; set; }
        public System.DateTime NGAYMUA { get; set; }
        public string NHAXUATBAN { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAPNHATTHONGTIN> CAPNHATTHONGTINs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
