//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.MUATAILIEUMOI = new HashSet<MUATAILIEUMOI>();
            this.NHANVIEN1 = new HashSet<NHANVIEN>();
            this.PHIEUMUON = new HashSet<PHIEUMUON>();
            this.PHIEUPHAT = new HashSet<PHIEUPHAT>();
            this.QUANLYTAILIEU = new HashSet<QUANLYTAILIEU>();
            this.THANHLYTAILIEU = new HashSet<THANHLYTAILIEU>();
        }
    
        public string MANV { get; set; }
        public string NQL_NV { get; set; }
        public string TENNV { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string GIOITINH { get; set; }
        public string EMAIL { get; set; }
        public string SODIENTHOAI { get; set; }
        public string VAITRO { get; set; }
        public string DIACHI { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
    
        public virtual ICollection<MUATAILIEUMOI> MUATAILIEUMOI { get; set; }
        public virtual ICollection<NHANVIEN> NHANVIEN1 { get; set; }
        public virtual NHANVIEN NHANVIEN2 { get; set; }
        public virtual ICollection<PHIEUMUON> PHIEUMUON { get; set; }
        public virtual ICollection<PHIEUPHAT> PHIEUPHAT { get; set; }
        public virtual ICollection<QUANLYTAILIEU> QUANLYTAILIEU { get; set; }
        public virtual ICollection<THANHLYTAILIEU> THANHLYTAILIEU { get; set; }
    }
}
