//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUPHAT
    {
        public string MAPHIEUPHAT { get; set; }
        public string MANV { get; set; }
        public string MAPHIEUMUON { get; set; }
        public float PHIPHAT { get; set; }
        public string LYDOPHAT { get; set; }
        public string SACHTHAYTHE { get; set; }
        public string TINHTRANGTAILIEU { get; set; }
        public string LYDO { get; set; }
        public Nullable<System.DateTime> NGTAO { get; set; }
        public string NGUOILAP { get; set; }
        public Nullable<int> SOLAN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHIEUMUON PHIEUMUON { get; set; }
    }
}
