//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUON
    {
        public PHIEUMUON()
        {
            this.CHITIETPHIEUMUON = new HashSet<CHITIETPHIEUMUON>();
            this.GIAHANTAILIEU = new HashSet<GIAHANTAILIEU>();
            this.PHIEUPHAT = new HashSet<PHIEUPHAT>();
            this.GIAHANTAILIEU1 = new HashSet<GIAHANTAILIEU>();
        }
    
        public string MAPHIEUMUON { get; set; }
        public string MANV { get; set; }
        public string MASOTHE { get; set; }
        public System.DateTime NGAYMUON { get; set; }
        public System.DateTime NGAYTRA { get; set; }
    
        public virtual ICollection<CHITIETPHIEUMUON> CHITIETPHIEUMUON { get; set; }
        public virtual ICollection<GIAHANTAILIEU> GIAHANTAILIEU { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THEBANDOC THEBANDOC { get; set; }
        public virtual ICollection<PHIEUPHAT> PHIEUPHAT { get; set; }
        public virtual ICollection<GIAHANTAILIEU> GIAHANTAILIEU1 { get; set; }
    }
}
