//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUMUON()
        {
            this.CHITIETPHIEUMUONs = new HashSet<CHITIETPHIEUMUON>();
            this.GIAHANTAILIEUx = new HashSet<GIAHANTAILIEU>();
            this.PHIEUPHATs = new HashSet<PHIEUPHAT>();
            this.GIAHANTAILIEUx1 = new HashSet<GIAHANTAILIEU>();
        }
    
        public string MAPHIEUMUON { get; set; }
        public string MANV { get; set; }
        public string MASOTHE { get; set; }
        public System.DateTime NGAYMUON { get; set; }
        public System.DateTime NGAYTRA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUMUON> CHITIETPHIEUMUONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAHANTAILIEU> GIAHANTAILIEUx { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THEBANDOC THEBANDOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUPHAT> PHIEUPHATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAHANTAILIEU> GIAHANTAILIEUx1 { get; set; }
    }
}
