//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGHOC
    {
        public PHONGHOC()
        {
            this.DATPHONG = new HashSet<DATPHONG>();
            this.DATPHONG1 = new HashSet<DATPHONG>();
        }
    
        public string MAPHONG { get; set; }
        public string TENPHONG { get; set; }
        public int SUCCHUA { get; set; }
        public string TRANGBI { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual ICollection<DATPHONG> DATPHONG { get; set; }
        public virtual ICollection<DATPHONG> DATPHONG1 { get; set; }
    }
}
