//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAILIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAILIEU()
        {
            this.CAPNHATTHONGTINs = new HashSet<CAPNHATTHONGTIN>();
            this.CHITIETDATTRUOCs = new HashSet<CHITIETDATTRUOC>();
            this.CHITIETPHIEUMUONs = new HashSet<CHITIETPHIEUMUON>();
            this.QUANLYTAILIEUx = new HashSet<QUANLYTAILIEU>();
        }
    
        public string MATAILIEU { get; set; }
        public string TENSACH { get; set; }
        public string NGONNGU { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<float> PHIMUON { get; set; }
        public string THELOAI { get; set; }
        public string TENTACGIA { get; set; }
        public string NXB { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAPNHATTHONGTIN> CAPNHATTHONGTINs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATTRUOC> CHITIETDATTRUOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUMUON> CHITIETPHIEUMUONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANLYTAILIEU> QUANLYTAILIEUx { get; set; }
    }
}
