//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAILIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAILIEU()
        {
            this.CAPNHATTHONGTIN = new HashSet<CAPNHATTHONGTIN>();
            this.CHITIETDATTRUOC = new HashSet<CHITIETDATTRUOC>();
            this.CHITIETPHIEUMUON = new HashSet<CHITIETPHIEUMUON>();
            this.QUANLYTAILIEU = new HashSet<QUANLYTAILIEU>();
        }
    
        public string MATAILIEU { get; set; }
        public string TENSACH { get; set; }
        public string NGONNGU { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<float> PHIMUON { get; set; }
        public string THELOAI { get; set; }
        public string TENTACGIA { get; set; }
        public string NXB { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAPNHATTHONGTIN> CAPNHATTHONGTIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATTRUOC> CHITIETDATTRUOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUMUON> CHITIETPHIEUMUON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANLYTAILIEU> QUANLYTAILIEU { get; set; }
    }
}
