//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHLYTAILIEU
    {
        public string MAHOADON { get; set; }
        public string MANV { get; set; }
        public System.DateTime NGAYTHANHLY { get; set; }
        public string TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
