//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEBANDOC
    {
        public THEBANDOC()
        {
            this.DATMUONTRUOC = new HashSet<DATMUONTRUOC>();
            this.DATPHONG = new HashSet<DATPHONG>();
            this.PHIEUMUON = new HashSet<PHIEUMUON>();
        }
    
        public string MASOTHE { get; set; }
        public string MATHANHVIEN { get; set; }
        public string TINHTRANGTHE { get; set; }
        public string HANSUDUNG { get; set; }
    
        public virtual ICollection<DATMUONTRUOC> DATMUONTRUOC { get; set; }
        public virtual ICollection<DATPHONG> DATPHONG { get; set; }
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual ICollection<PHIEUMUON> PHIEUMUON { get; set; }
    }
}
